### ISSUE TITLE
EF Core 2.0 Support

### ISSUE THREAD

**Issue by fabianosobreira** [AutoMapper/AutoMapper.EF6#15]
Any plans to support EF Core 2.0?

**Comment by jbogard** [comment]
Yes EF Core is supported today, this package isn’t needed for EF Core.

**Comment by SuperJMN** [comment]
Hey Jimmy! Do you mean that the AutoMapper package is bundled with all the features? :) Thanks in advance!

**Comment by jbogard** [comment]
No that it’s not needed. EF Core’s projections means you don’t need the
things in this package.

**Comment by SuperJMN** [comment]
I didn't know there was such a thing in EF Core! What do you mean?  I have "binged" for "EF Core projections" and got no relevant results. 

Big thanks!! (by the way, reading Los Techies every now and then. This is one of my favorite articles: https://lostechies.com/jimmybogard/2012/10/08/favor-query-objects-over-repositories/)

**Comment by jbogard** [comment]
What I mean by "projections" is "Select". EF Core supports "Select". If you
look at what AutoMapper.EF6 does, it just wraps a few things:

`queryable.ProjectTo<TDestination>().DecompileAsync().ToListAsync()`

The "DecompileAsync" isn't necessary because EF Core will detect things it
can't project and pull down the rest of the entity to execute in-memory for
you. So an "AutoMapper.EFCore" extension would just wrap `ProjectTo.ToList`
which I'm not sure provides a ton of value.

But maybe it does? It just wouldn't be tied to EF Core.

I could include these methods inside of AutoMapper as built-in extension
methods, but they'd collide with the AutoMapper.EF6 ones.

Maybe that's not a big deal?
